<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Random Variables | Statistics 371 Full Notes</title>
  <meta name="description" content="Introductory Applied Statistics for the Life Sciences" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Random Variables | Statistics 371 Full Notes" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Introductory Applied Statistics for the Life Sciences" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Random Variables | Statistics 371 Full Notes" />
  
  <meta name="twitter:description" content="Introductory Applied Statistics for the Life Sciences" />
  

<meta name="author" content="Miranda Rintoul" />


<meta name="date" content="2024-11-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="probability.html"/>
<link rel="next" href="estimation.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistics 371 Full Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction To Statistics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#statistics"><i class="fa fa-check"></i><b>1.1</b> Statistics</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#key-terms"><i class="fa fa-check"></i><b>1.2</b> Key terms</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#types-of-data"><i class="fa fa-check"></i><b>1.3</b> Types of data</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#course-outline"><i class="fa fa-check"></i><b>1.4</b> Course outline</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>2</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="2.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#histograms"><i class="fa fa-check"></i><b>2.1</b> Histograms</a></li>
<li class="chapter" data-level="2.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#location"><i class="fa fa-check"></i><b>2.2</b> Location</a></li>
<li class="chapter" data-level="2.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#spread"><i class="fa fa-check"></i><b>2.3</b> Spread</a></li>
<li class="chapter" data-level="2.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#box-plots"><i class="fa fa-check"></i><b>2.4</b> Box plots</a></li>
<li class="chapter" data-level="2.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#multiple-datasets"><i class="fa fa-check"></i><b>2.5</b> Multiple datasets</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>3</b> Probability</a>
<ul>
<li class="chapter" data-level="3.1" data-path="probability.html"><a href="probability.html#sampling"><i class="fa fa-check"></i><b>3.1</b> Sampling</a></li>
<li class="chapter" data-level="3.2" data-path="probability.html"><a href="probability.html#probability-basics"><i class="fa fa-check"></i><b>3.2</b> Probability basics</a></li>
<li class="chapter" data-level="3.3" data-path="probability.html"><a href="probability.html#conditional-probability"><i class="fa fa-check"></i><b>3.3</b> Conditional probability</a></li>
<li class="chapter" data-level="3.4" data-path="probability.html"><a href="probability.html#independence"><i class="fa fa-check"></i><b>3.4</b> Independence</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="random-variables.html"><a href="random-variables.html"><i class="fa fa-check"></i><b>4</b> Random Variables</a>
<ul>
<li class="chapter" data-level="4.1" data-path="random-variables.html"><a href="random-variables.html#random-variable-basics"><i class="fa fa-check"></i><b>4.1</b> Random variable basics</a></li>
<li class="chapter" data-level="4.2" data-path="random-variables.html"><a href="random-variables.html#expectation-and-variance"><i class="fa fa-check"></i><b>4.2</b> Expectation and variance</a></li>
<li class="chapter" data-level="4.3" data-path="random-variables.html"><a href="random-variables.html#binomial-random-variables"><i class="fa fa-check"></i><b>4.3</b> Binomial random variables</a></li>
<li class="chapter" data-level="4.4" data-path="random-variables.html"><a href="random-variables.html#rules-of-expectation-and-variance"><i class="fa fa-check"></i><b>4.4</b> Rules of expectation and variance</a></li>
<li class="chapter" data-level="4.5" data-path="random-variables.html"><a href="random-variables.html#normal-random-variables"><i class="fa fa-check"></i><b>4.5</b> Normal random variables</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="estimation.html"><a href="estimation.html"><i class="fa fa-check"></i><b>5</b> Estimation</a>
<ul>
<li class="chapter" data-level="5.1" data-path="estimation.html"><a href="estimation.html#estimation-1"><i class="fa fa-check"></i><b>5.1</b> Estimation</a></li>
<li class="chapter" data-level="5.2" data-path="estimation.html"><a href="estimation.html#sampling-distributions"><i class="fa fa-check"></i><b>5.2</b> Sampling distributions</a></li>
<li class="chapter" data-level="5.3" data-path="estimation.html"><a href="estimation.html#central-limit-theorem"><i class="fa fa-check"></i><b>5.3</b> Central Limit Theorem</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="confidence-intervals.html"><a href="confidence-intervals.html"><i class="fa fa-check"></i><b>6</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="6.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#z-confidence-interval"><i class="fa fa-check"></i><b>6.1</b> Z confidence interval</a></li>
<li class="chapter" data-level="6.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#confidence-interval-interpretation"><i class="fa fa-check"></i><b>6.2</b> Confidence interval interpretation</a></li>
<li class="chapter" data-level="6.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#t-confidence-interval"><i class="fa fa-check"></i><b>6.3</b> T confidence interval</a></li>
<li class="chapter" data-level="6.4" data-path="confidence-intervals.html"><a href="confidence-intervals.html#proportion-ci"><i class="fa fa-check"></i><b>6.4</b> Proportion CI</a></li>
<li class="chapter" data-level="6.5" data-path="confidence-intervals.html"><a href="confidence-intervals.html#bootstrap-confidence-interval"><i class="fa fa-check"></i><b>6.5</b> Bootstrap confidence interval</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>7</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-sample-t-test"><i class="fa fa-check"></i><b>7.1</b> One-sample T test</a></li>
<li class="chapter" data-level="7.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#errors"><i class="fa fa-check"></i><b>7.2</b> Errors</a></li>
<li class="chapter" data-level="7.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-sided-tests"><i class="fa fa-check"></i><b>7.3</b> One-sided tests</a></li>
<li class="chapter" data-level="7.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-sample-z-test"><i class="fa fa-check"></i><b>7.4</b> One-sample Z test</a></li>
<li class="chapter" data-level="7.5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#power"><i class="fa fa-check"></i><b>7.5</b> Power</a></li>
<li class="chapter" data-level="7.6" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#bootstrap-test"><i class="fa fa-check"></i><b>7.6</b> Bootstrap test</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="other-one-sample-tests.html"><a href="other-one-sample-tests.html"><i class="fa fa-check"></i><b>8</b> Other One-Sample Tests</a>
<ul>
<li class="chapter" data-level="8.1" data-path="other-one-sample-tests.html"><a href="other-one-sample-tests.html#one-sample-proportion-test"><i class="fa fa-check"></i><b>8.1</b> One-sample proportion test</a></li>
<li class="chapter" data-level="8.2" data-path="other-one-sample-tests.html"><a href="other-one-sample-tests.html#median-test"><i class="fa fa-check"></i><b>8.2</b> Median test</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="two-sample-testing.html"><a href="two-sample-testing.html"><i class="fa fa-check"></i><b>9</b> Two-Sample Testing</a>
<ul>
<li class="chapter" data-level="9.1" data-path="two-sample-testing.html"><a href="two-sample-testing.html#equal-variances-t-test"><i class="fa fa-check"></i><b>9.1</b> Equal variances T test</a></li>
<li class="chapter" data-level="9.2" data-path="two-sample-testing.html"><a href="two-sample-testing.html#unequal-variances-t-test"><i class="fa fa-check"></i><b>9.2</b> Unequal variances T test</a></li>
<li class="chapter" data-level="9.3" data-path="two-sample-testing.html"><a href="two-sample-testing.html#two-sample-proportion-test"><i class="fa fa-check"></i><b>9.3</b> Two-sample proportion test</a></li>
<li class="chapter" data-level="9.4" data-path="two-sample-testing.html"><a href="two-sample-testing.html#two-sample-bootstrap-test"><i class="fa fa-check"></i><b>9.4</b> Two-sample bootstrap test</a></li>
<li class="chapter" data-level="9.5" data-path="two-sample-testing.html"><a href="two-sample-testing.html#rank-sum-test"><i class="fa fa-check"></i><b>9.5</b> Rank sum test</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="testing-paired-data.html"><a href="testing-paired-data.html"><i class="fa fa-check"></i><b>10</b> Testing Paired Data</a>
<ul>
<li class="chapter" data-level="10.1" data-path="testing-paired-data.html"><a href="testing-paired-data.html#paired-t-test"><i class="fa fa-check"></i><b>10.1</b> Paired T test</a></li>
<li class="chapter" data-level="10.2" data-path="testing-paired-data.html"><a href="testing-paired-data.html#signed-rank-test"><i class="fa fa-check"></i><b>10.2</b> Signed rank test</a></li>
<li class="chapter" data-level="10.3" data-path="testing-paired-data.html"><a href="testing-paired-data.html#median-test-1"><i class="fa fa-check"></i><b>10.3</b> Median test</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>11</b> Analysis of Variance</a>
<ul>
<li class="chapter" data-level="11.1" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#more-than-two-groups"><i class="fa fa-check"></i><b>11.1</b> More than two groups</a></li>
<li class="chapter" data-level="11.2" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#variance-decomposition"><i class="fa fa-check"></i><b>11.2</b> Variance decomposition</a></li>
<li class="chapter" data-level="11.3" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#anova-test"><i class="fa fa-check"></i><b>11.3</b> ANOVA test</a></li>
<li class="chapter" data-level="11.4" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#post-hoc-analysis"><i class="fa fa-check"></i><b>11.4</b> Post-hoc analysis</a></li>
<li class="chapter" data-level="11.5" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#non-normal-data"><i class="fa fa-check"></i><b>11.5</b> Non-normal data</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>12</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="12.1" data-path="linear-regression.html"><a href="linear-regression.html#correlation"><i class="fa fa-check"></i><b>12.1</b> Correlation</a></li>
<li class="chapter" data-level="12.2" data-path="linear-regression.html"><a href="linear-regression.html#linear-modeling"><i class="fa fa-check"></i><b>12.2</b> Linear modeling</a></li>
<li class="chapter" data-level="12.3" data-path="linear-regression.html"><a href="linear-regression.html#testing-slope"><i class="fa fa-check"></i><b>12.3</b> Testing slope</a></li>
<li class="chapter" data-level="12.4" data-path="linear-regression.html"><a href="linear-regression.html#prediction"><i class="fa fa-check"></i><b>12.4</b> Prediction</a></li>
<li class="chapter" data-level="12.5" data-path="linear-regression.html"><a href="linear-regression.html#coefficient-of-determination"><i class="fa fa-check"></i><b>12.5</b> Coefficient of determination</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html"><i class="fa fa-check"></i><b>13</b> Categorical Data Analysis</a>
<ul>
<li class="chapter" data-level="13.1" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#goodness-of-fit-test"><i class="fa fa-check"></i><b>13.1</b> Goodness-of-fit test</a></li>
<li class="chapter" data-level="13.2" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#one-sample-proportion-test-1"><i class="fa fa-check"></i><b>13.2</b> One-sample proportion test</a></li>
<li class="chapter" data-level="13.3" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#independence-test"><i class="fa fa-check"></i><b>13.3</b> Independence test</a></li>
<li class="chapter" data-level="13.4" data-path="categorical-data-analysis.html"><a href="categorical-data-analysis.html#two-sample-proportion-test-1"><i class="fa fa-check"></i><b>13.4</b> Two-sample proportion test</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistics 371 Full Notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="random-variables" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Random Variables<a href="random-variables.html#random-variables" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><img src="figs/comics/ch4.png" height="450px" style="display: block; margin: auto;" /></p>
<p>Sections 2-3 cover the basic, fundamental tools that we need to do statistics. Now, we’re going to go deeper into the mathematical theory that our methods are based on.</p>
<p><img src="figs/rvs/371_notes4.png" /><!-- --></p>
<div id="random-variable-basics" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Random variable basics<a href="random-variables.html#random-variable-basics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We’ve seen how to represent and calculate the probability of different events happening when we sample from a population. But often, instead of <em>qualitative</em> events, we’re interested in particular <em>numeric</em> values of the population. In the hybrid vehicles example, each item has an associated number that refers to its MPG.</p>
<div class="infobox deff">
<p>A <strong>random variable</strong> (RV) represents the distribution of numeric values in a population.</p>
</div>
<p>We use capital letters to refer to random variables, e.g. <span class="math inline">\(X =\)</span> a vehicle’s MPG. The value of a RV is random, because different objects in the population have different values. We can think of a RV as a “plan” to sample an item from the population. We don’t know what the value will be until we actually measure it.</p>
<hr />
<div class="infobox deff">
<p>When an item from the population is actually measured, the random variable will <strong>realize</strong> a constant value.</p>
</div>
<p>If we choose a car at random and it turns out to have 46 MPG, then <span class="math inline">\(X = 46\)</span>. When the realization is unkown, it is denoted by a lowercase letter of the same type.
<span class="math display">\[X = \text{ random variable},\quad\quad x = \text{ constant realization}\]</span>
Similar to how we talk about the probability of events, we’re interested in the probability that <span class="math inline">\(X\)</span> takes on a certain value <span class="math inline">\(x\)</span>. For the vehicle example, <span class="math inline">\(\mathbb{P}(X = 46)\)</span> is the probability of drawing a vehicle with MPG 46, which is the same as the proportion of vehicles with MPG 46.</p>
<div class="infobox deff">
<p>In general, the <strong>probability function</strong> on <span class="math inline">\(X\)</span> assigns a probability to each possible value of <span class="math inline">\(X\)</span>. We write this as <span class="math inline">\(P(X = x)\)</span>.</p>
</div>
<hr />
<p>There are two types of RVs, <strong>discrete</strong> and <strong>continuous</strong>. This is analogous to the difference between discrete and continuous data.</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<div class="infobox deff">
<p>A discrete random variable can only take on specific values.</p>
</div>
<ul>
<li>Result of a die roll</li>
<li>Number of people in a household</li>
</ul>
<div class="infobox deff">
<p>A continuous random variable can take on any value in a range, and it’s impossible for us to “list out” the possible values.</p>
</div>
<ul>
<li>Person’s height</li>
<li>Time to walk to class</li>
</ul>
<p>Think of a RV as representing the spread of all possible values in a population. If we sample from a discrete RV/population, we get discrete data. If we sample from a continuous RV/population, we get continuous data.</p>
<hr />
<p>Because discrete RVs take on specific values, we can enumerate those values and probabilities in a table. For example, the Apgar score for newborns is on a scale from 0-10 based on condition immediately after birth.</p>
<table>
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th>0</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\mathbb{P}(X = x)\)</span></td>
<td>0.001</td>
<td>0.006</td>
<td>0.007</td>
<td>0.008</td>
<td>0.012</td>
<td>0.020</td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th>6</th>
<th>7</th>
<th>8</th>
<th>9</th>
<th>10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\mathbb{P}(X = x)\)</span></td>
<td>0.038</td>
<td>0.099</td>
<td>0.319</td>
<td>0.437</td>
<td>0.053</td>
</tr>
</tbody>
</table>
<p>The row labeled <span class="math inline">\(P(X = x)\)</span> shows the probability function for <span class="math inline">\(X\)</span>.</p>
<div class="infobox deff">
<p>For a discrete RV, the probability function has a specific name: the <strong>probability mass function</strong> (pmf).</p>
</div>
<p>We see that if we sample a newborn at random from the population, there is a 43.7% chance that it has an Apgar score of 9. Equivalently, the proportion of newbors with Apgar score 9 is 0.437.</p>
<p>It’s important to point out that all of the probabilities in this table must add up to 1. In other words, every single item in this population must have a score from 0 to 10.</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<hr />
<p>Sometimes, a “population” represents the possible results of some kind of random experiment. If our experiment is to roll a fair six-sided die, then we can think of this roll as being a random sample from a population with values 1, 2, 3, 4, 5, and 6.</p>
<p>Another common type of experiment is <em>binary</em>, which means there are only two possible outcomes. We might be interested in repeating a binary experiment several times and seeing how many times we get the two different outcomes. For example, flip a coin 10 times and count how many times we get heads.</p>
<p>Let’s look at a more “real” example. Offspring of a dihybrid cross of peas can have any of four phenotypes. <span class="math inline">\(\frac{9}{16}\)</span> offspring have the round-yellow (RY) type. We breed the peas 3 times, and count the number of RY offspring out of 3.</p>
<p>We can see anywhere from 0 to 3 RY plants, so the population represeting this experiment has four values: 0, 1, 2, or 3. Let’s make a table to keep track of these different outcomes.</p>
<table>
<thead>
<tr class="header">
<th>Result</th>
<th align="center"><span class="math inline">\(x\)</span></th>
<th><span class="math inline">\(\mathbb{P}(X = x)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>FFF</td>
<td align="center">0</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td align="center">1</td>
<td></td>
</tr>
<tr class="odd">
<td>SSF, SFS, FSS</td>
<td align="center">2</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td align="center">3</td>
<td></td>
</tr>
</tbody>
</table>
<p>So, the random variable <span class="math inline">\(X\)</span> represents our random experiment, which is the number of RY plants we get out of three breedings. When working with a binary experiment, it is conventional to define one outcome as a “success” and one as a “failure”. In our case, a success is when we get an RY plant.</p>
<p>Let’s think about how to find these probabilities. What is <span class="math inline">\(P(X = 0)\)</span>? This means that we bred the plant three times, but had no RY offspring. We had to get three failures in a row, which is represented by the result “FFF”. If we assume the offspring are independent, then the probability of this happening is the <span class="math inline">\(\frac{7}{16}\)</span> probability of failure, three times in a row.
<span class="math display">\[P(X = 0) \;=\; P(FFF) \;=\; \frac{7}{16}\cdot \frac{7}{16}\cdot \frac{7}{16} = 0.084\]</span></p>
<p>What about <span class="math inline">\(P(X = 2)\)</span>? That means that we bred the plant three times, and 2 out of 3 offspring were RY. We have to be a bit careful here, because there are multiple ways that this can happen. We might get two RY plants, then one non-RY plant (SSF). Or we might get an RY plant, a non-RY plant, then another RY plant (SFS). The last way is if we get FSS.</p>
<p>We need to take all three of these possibilities into account when finding the probability, because they all lead to <span class="math inline">\(X\)</span> being equal to 2. The individual probabilities are found by multiplying the probabilities for two successes and one failure.
<span class="math display">\[P(SSF) \;=\; P(SFS) \;=\; P(FSS) \;=\; \frac{9}{16}\cdot \frac{9}{16}\cdot \frac{7}{16}\]</span></p>
<p>We have multiply this probability by three, to account for the different ways this can happen. So,
<span class="math display">\[P(X = 2) \;=\; P(SSF) + P(SFS) + P(FSS) \;=\; 3\cdot \frac{9}{16}\cdot \frac{9}{16}\cdot \frac{7}{16} \;=\; 0.415.\]</span></p>
<hr />
<div class="infobox exer">
<p>Fill out the rest of the table by finding the results and probabilities for <span class="math inline">\(X = 1\)</span> and <span class="math inline">\(X = 3\)</span>.</p>
<table>
<thead>
<tr class="header">
<th>Result</th>
<th align="center"><span class="math inline">\(x\)</span></th>
<th align="center"><span class="math inline">\(\mathbb{P}(X = x)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>FFF</td>
<td align="center">0</td>
<td align="center"></td>
</tr>
<tr class="even">
<td></td>
<td align="center">1</td>
<td align="center"></td>
</tr>
<tr class="odd">
<td>SSF, SFS, FSS</td>
<td align="center">2</td>
<td align="center"></td>
</tr>
<tr class="even">
<td></td>
<td align="center">3</td>
<td align="center"></td>
</tr>
</tbody>
</table>
<p><span style="color:#8601AF">
<span class="math inline">\(X = 1\)</span> means that one plant out of three breedings had the RY type. There are three ways this can happen: SFF, FSF, FFS. Each one of those individual results has probability
<span class="math display">\[\frac{9}{16}\cdot \frac{7}{16}\cdot \frac{7}{16}.\]</span>
So, the overall probability <span class="math inline">\(P(X = 1)\)</span> is
<span class="math display">\[P(SFF) + P(FSF) + P(FFS) \;=\; 3\cdot \frac{9}{16}\cdot \frac{7}{16}\cdot \frac{7}{16} \;=\; 0.323.\]</span>
</span></p>
<p><span style="color:#8601AF">
<span class="math inline">\(X = 3\)</span> means that every single one of the three offspring were RY There’s only one way this can happen: we get three succeses in a row, SSS.
<span class="math display">\[P(X = 3) \;=\; P(SSS) \;=\; \frac{9}{16}\cdot \frac{9}{16}\cdot \frac{9}{16} \;=\; 0.178\]</span>
</span></p>
</div>
<table>
<thead>
<tr class="header">
<th>Result</th>
<th align="center"><span class="math inline">\(x\)</span></th>
<th align="center"><span class="math inline">\(\mathbb{P}(X = x)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>FFF</td>
<td align="center">0</td>
<td align="center">0.084</td>
</tr>
<tr class="even">
<td>SFF, FSF, FFS</td>
<td align="center">1</td>
<td align="center">0.323</td>
</tr>
<tr class="odd">
<td>SSF, SFS, FSS</td>
<td align="center">2</td>
<td align="center">0.415</td>
</tr>
<tr class="even">
<td>SSS</td>
<td align="center">3</td>
<td align="center">0.178</td>
</tr>
</tbody>
</table>
<p>We can check that we’ve done this correctly by checking if the probabilities add to 1. <span class="math inline">\(0.084 + 0.323 + 0.415 + 0.178 = 1\)</span>.</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<hr />
<div class="infobox exer">
<p>Consider the event that “at least one of the offspring will be RY.” How can we write this qualitative event as a numerical statement about <span class="math inline">\(X\)</span>? What is the probability of this happening?</p>
<p><span style="color:#8601AF">
“At least one” means we see either 1, 2, or 3 RY offspring (anything except 0). We can write this as <span class="math inline">\(P(X \ge 1)\)</span>. It’s also equivalent to say <span class="math inline">\(P(X \neq 0)\)</span> or <span class="math inline">\(P(X &gt; 0)\)</span>. We can find this probability directly:
<span class="math display">\[P(X \ge 1) \;=\; P(1) + P(2) + P(3) \;=\; 0.323 + 0.415 + 0.178 \;=\; 0.916\]</span>
Or with the complement rule:
<span class="math display">\[P(X \neq 0) \;=\; 1 - P(0) \;=\; 1 - 0.084 \;=\; 0.916.\]</span>
</span></p>
</div>
</div>
<div id="expectation-and-variance" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Expectation and variance<a href="random-variables.html#expectation-and-variance" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We’ve learned about the concept of using the mean, or average, to describe the center of a set of observed data. We can apply this same concept to a random variable. Since RVs represent populations, the mean of a RV is interpreted as the <em>true population mean</em>. This is a parameter.</p>
<p>How do we take an average when we have a table of values and probabilities, rather than a list of data points? Consider a population where 90% of the values are 0, and 10% of the values are 1.</p>
<table>
<thead>
<tr class="header">
<th align="center"><span class="math inline">\(x\)</span></th>
<th align="center"><span class="math inline">\(\mathbb{P}(X = x)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">0</td>
<td align="center">0.9</td>
</tr>
<tr class="even">
<td align="center">1</td>
<td align="center">0.1</td>
</tr>
</tbody>
</table>
<p>If we draw a random item from this population, there’s a 90% chance of it having a value of 0. We need to take an average of the population values, which are 0 and 1.</p>
<p>Intuitively, it doesn’t make sense to say the population mean is the simple average <span class="math inline">\((1 + 0)/2 = 0.5\)</span>. There are many more 0’s than 1’s in the population, and 0.5 seems inappropriate because it is exactly halfway between 0 and 1. We need to take the probabilities into account.</p>
<p>Instead of taking a simple average, we calculate the mean of a RV by taking a <em>weighted</em> average of its values. The weights are the associated probabilities. By doing this, we can take into account the frequencies that each value appears in the population. In the above example, the mean is
<span class="math display">\[(0)0.9 + (1)0.1 \;=\; 0.1 \; = \; E(X)\]</span></p>
<p>The mean of 0.1 is much closer to 0 than 1, which corresponds to the fact that there are way more 0’s than 1’s in our population.</p>
<p>Another name for the mean of a RV (which is the mean of a population) is <strong>expected value</strong> or <strong>expectation</strong>. The expected value is trying to describe the “typical” draw from the population. It’s still perfectly fine to use the terms “mean” or “average” in this context, but you should specify that you are talking about the mean of a RV rather than the mean of a sample.</p>
<hr />
<div class="infobox deff">
<p>In general, the <strong>expected value</strong> of a discrete RV is a weighted average of the possible values, where the weights are the probabilities.
<span class="math display">\[\mathbb{E}(X) \;=\; \mu \;=\;  \sum_x P(X = x) \cdot x\]</span></p>
</div>
<p>Here, we’re using <span class="math inline">\(x\)</span> to represent enumerating over all of the possible values of <span class="math inline">\(X\)</span>. We can also use the Greek letter <span class="math inline">\(\mu\)</span> (mu, pronounced “mew”).<br />
<span class="math display">\[E(X) \;=\; \mu  \;=\; ``\text{RV mean&quot;} \;=\; ``\text{Population mean&quot;}\]</span></p>
<p>Suppose the random variable <span class="math inline">\(X_1\)</span> is the value of a roll of a fair six-sided die. The possible values of <span class="math inline">\(X_1\)</span> are 1, 2, 3, 4, 5, 6, and each has equal probability. So,
<span class="math display">\[E(X_1) \;=\; (1)\frac{1}{6} + (2)\frac{1}{6} + (3)\frac{1}{6} + (4)\frac{1}{6} + (5)\frac{1}{6} + (6)\frac{1}{6} \;=\; 3.5\]</span>
In the case where all of the population values are equally likely, calculating the expected value is equivalent to calculating a simple average. But this usually is not the case.</p>
<p>Suppose <span class="math inline">\(X_2\)</span> is the value of the roll of an unfair die, where <span class="math inline">\(P(1) = \frac{1}{12}\)</span> and <span class="math inline">\(P(6) = \frac{3}{12}\)</span>. Then
<span class="math display">\[E(X_2) \;=\; (1)\frac{1}{12} + (2)\frac{1}{6} + (3)\frac{1}{6} + (4)\frac{1}{6} + (5)\frac{1}{6} + (6)\frac{3}{12} \;=\; 3.917\]</span>
We see that <span class="math inline">\(X_2\)</span> has a higher expected value than <span class="math inline">\(X_1\)</span>. If you repeatedly rolled die <span class="math inline">\(X_1\)</span> and your friend repeatedly rolled die <span class="math inline">\(X_2\)</span>, then you might notice that your friend tends to get higher rolls.</p>
<hr />
<p>So what exactly is the connection between an expected value/population mean and the sample mean?<br />
<span class="math display">\[\text{Sample mean} \;=\; \bar{x} \;=\; \frac{1}{n}\sum_{i=1}^n x_i\]</span>
<span class="math inline">\(\bar{x}\)</span> is the observed mean of some measured data. It is a <em>statistic</em>.</p>
<p>The expected value <span class="math inline">\(E(X) = \mu\)</span> is the mean of the <em>entire</em> population. It is a <em>parameter</em>. If we took a sample from a population with mean <span class="math inline">\(\mu\)</span>, then the sample mean <span class="math inline">\(\bar{x}\)</span> would probably look similar to <span class="math inline">\(\mu\)</span>.</p>
<p>If we were somehow able to take a sample of infinite <span class="math inline">\(x_i\)</span>’s and take their sample mean, <span class="math inline">\(\bar{x}\)</span> would be equal to <span class="math inline">\(\mu\)</span>.</p>
<hr />
<p>We can also apply the concept of variance to describe the spread of a random variable. Since RVs represent populations, the variance of a RV is interpreted as the <em>true population variance</em>. This is a parameter.</p>
<p>Recall that variance is a measure of how close values are to their mean. Specifically, it is the average squared distance from the values to the mean. For RVs, the mean is given by expected value. The squared distance from a specific RV value <span class="math inline">\(x\)</span> to the mean of the RV is
<span class="math display">\[[x - E(X)]^2.\]</span>
Now, we need to take an average of these values to get the variance of the random variable. Just like before, we have to take a <em>weighted</em> average based on the probabilities <span class="math inline">\(P(X = x)\)</span>.</p>
<div class="infobox deff">
<p>The variance of a discrete RV, interpreted as the population variance, is
<span class="math display">\[V(X) \;=\; \sigma^2 \;=\; \sum_x P(X = x) \cdot [x-E(X)]^2\]</span></p>
</div>
<p>For each <span class="math inline">\(x\)</span>, we find the squared distance between <span class="math inline">\(x\)</span> and <span class="math inline">\(E(X)\)</span>, then multiply it by the probability of <span class="math inline">\(x\)</span>. We do this for all values in the RV, then add them up. We use the Greek letter <span class="math inline">\(\sigma^2\)</span> (sigma squared) to represent variance.
<span class="math display">\[V(X) \;=\; \sigma^2  \;=\; ``\text{RV variance&quot;} \;=\; ``\text{Population variance&quot;}\]</span></p>
<p>For example, recall the variable <span class="math inline">\(X_1\)</span> which describes the roll of a fair die. The mean of <span class="math inline">\(X_1\)</span> is <span class="math inline">\(E(X_1) = 3.5\)</span>, so the variance is <span class="math display">\[\begin{align*}
V(X) &amp;= \frac{1}{6}(1 - 3.5)^2 + \frac{1}{6}(2 - 3.5)^2 + \frac{1}{6}(3 - 3.5)^2 \\
&amp;+ \frac{1}{6}(4 - 3.5)^2 + \frac{1}{6}(5 - 3.5)^2 + \frac{1}{6}(6 - 3.5)^2
\end{align*}\]</span>
which is 2.917. We can interpret this as the uncertainty in the value we get when rolling a die.</p>
<p>Previously, we used both standard deviation and variance to describe spread. Standard deviation is the square root of the variance. We can say the exact same thing for a RV.</p>
<div class="infobox deff">
<p>The population standard deviation is given by <span class="math inline">\(\sigma\)</span>, where
<span class="math display">\[\sigma \;=\; \sqrt{\sigma^2} \;=\; \sqrt{V(X)}\]</span></p>
</div>
<p>Variance is in squared units compared to the original population, and standard deviation is in the original units of the population. But they provide the same information about spread.</p>
<hr />
<p>We can also look at the connection between a RV’s variance and the sample variance. For a set of data,
<span class="math display">\[\text{Sample variance} \;=\; s^2 \;=\; \frac{1}{n-1}\sum_{i=1}^n (x_i - \bar{x})^2\]</span>
<span class="math inline">\(s^2\)</span> is the observed variance, a <em>statistic</em>.</p>
<p>The variance of a RV, <span class="math inline">\(V(X) = \sigma^2\)</span> is the variance of the <em>entire</em> population, so it is a . If we took a sample from a population with variance <span class="math inline">\(\sigma^2\)</span>, then the sample variance <span class="math inline">\(s^2\)</span> would probably look similar to <span class="math inline">\(\sigma^2\)</span>.</p>
<p>If we were somehow able to take a sample of infinite <span class="math inline">\(x_i\)</span>’s and take their sample variance, <span class="math inline">\(s^2\)</span> would be equal to <span class="math inline">\(\sigma^2\)</span>.</p>
<hr />
<p>Conventionally, we use Latin letters to refer to statistics, and Greek letters to refer to parameters.</p>
<table>
<thead>
<tr class="header">
<th align="center">Measure</th>
<th align="center">Statistic</th>
<th align="center">Parameter</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Mean</td>
<td align="center"><span class="math inline">\(\bar{x}\)</span></td>
<td align="center"><span class="math inline">\(\mu\)</span></td>
</tr>
<tr class="even">
<td align="center">Variance</td>
<td align="center"><span class="math inline">\(s^2\)</span></td>
<td align="center"><span class="math inline">\(\sigma^2\)</span></td>
</tr>
<tr class="odd">
<td align="center">St. Dev.</td>
<td align="center"><span class="math inline">\(s\)</span></td>
<td align="center"><span class="math inline">\(\sigma\)</span></td>
</tr>
</tbody>
</table>
<hr />
<p>Let’s go back to the pea plant offspring example.</p>
<table>
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th>0</th>
<th>1</th>
<th>2</th>
<th>3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(P(X = x)\)</span></td>
<td>0.084</td>
<td>0.323</td>
<td>0.415</td>
<td>0.178</td>
</tr>
</tbody>
</table>
<div class="infobox exer">
<p>Find the mean (expected value), variance, and standard deviation of <span class="math inline">\(X\)</span>, the number of RY plants in 3 dihybrid offspring.</p>
<p><span style="color:#8601AF">
We need to weight each possible value 0-3 by its probability, then add them up. From the formula above, the expected value is
<span class="math display">\[E(X) \;=\; \sum_x P(X = x) \cdot x \;=\; 0.084(0) + 0.323(1) + 0.415(2) + 0.178(3) \;=\; 1.687\]</span>
The variance is a weighted average of the squared distance from the RV to the mean 1.687. This is
<span class="math display">\[\begin{align*}
V(X) &amp;= 0.084(0 - 1.687)^2 + 0.323(1 - 1.687)^2 + \\
&amp;+ 0.415(2 - 1.687)^2 + 0.178(3 - 1.687)^2 \\
&amp;= 0.739
\end{align*}\]</span>
The standard deviation is the square root of the variance, <span class="math inline">\(\sqrt{0.739} = 0.86.\)</span>
</span></p>
</div>
</div>
<div id="binomial-random-variables" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Binomial random variables<a href="random-variables.html#binomial-random-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The RV <span class="math inline">\(X\)</span> in the genes example represents a count of how many times we get an RY plant in 3 breedings. This is just one specific example of a more general structure of experiment. There are a lot of binary experiments with only two results that we might be interested in. For example, is a patient positive or negative for a disease? Did the value of a stock rise or fall?</p>
<p><span class="math inline">\(X\)</span> is called a <strong>binomial</strong> random variable. This is a specific type of discrete RV that counts the number of times a successful outcome occurs when we repeat a binary experiment.</p>
<p>We say that <span class="math inline">\(X\)</span> has a <strong>binomial distribution</strong>. The word “distribution” is used to refer to how probabilities are distributed across the different values in a population.</p>
<p><span class="math inline">\(X\)</span> is one particular example of a binomial, but all binomial RVs share specific properties. Let’s see how to identify and define a binomial RV.</p>
<p>The three trials in the plant breeding experiment have specific properties:</p>
<ul>
<li>They only yield one of two outcomes (success, or failure). We defined a “success” as seeing an RY type plant.</li>
<li>They all have the same probability of success. In the plant example, <span class="math inline">\(\pi = 9/16\)</span>.
<span class="math display">\[P(\text{success}) = \pi,\quad P(\text{failure}) = 1 - \pi\]</span></li>
<li>They are independent.</li>
</ul>
<div class="infobox deff">
<p>To define a <strong>binomial</strong> random variable, we need to binary, identical, independent trials. Our binomial RV count the number of successes in a fixed number (<span class="math inline">\(n\)</span>) of those trials.</p>
</div>
<p>To make statements about a binomial RV, there are two values that we need to define. <span class="math inline">\(\pi\)</span>, the probability of success, and <span class="math inline">\(n\)</span>, the number of trials or experimental runs we observe.</p>
<div class="infobox exer">
<p>Why are following situations not binomial RVs?</p>
<ul>
<li>We breed plants until we get an RY, then stop.</li>
<li>We counted up how many times we get each of the four phenotypes, not just RY.</li>
</ul>
<p><span style="color:#8601AF">
The first example is not binomial because there is not a fixed number of trials <span class="math inline">\(n\)</span>. The second example is not binomial because there are four possible outcomes, but we need there to be only two.
</span></p>
</div>
<hr />
<p>If <span class="math inline">\(X\)</span> is binomial, we write <span class="math inline">\(X \sim Binom(\# trials,\; \textit{success-prob})\)</span>. The plant RV is <span class="math inline">\(Binom(3, \frac{9}{16})\)</span> More generally, <span class="math inline">\(X \sim Binom(n, \pi)\)</span>.</p>
<div class="infobox deff">
<p>The <span class="math inline">\(\sim\)</span> symbol means the random variable follows a specific type of distribution.</p>
</div>
<p>The pmf (probability mass function) of <span class="math inline">\(X\)</span> has a special formula. In the genes example, we found
<span class="math display">\[P(X = 2) \;=\; 3(9/16)^2(7/16)^1.\]</span>
We multiply <span class="math inline">\(\frac{9}{16}\)</span> twice because we have two succesess, and <span class="math inline">\(\frac{7}{16}\)</span> once because we have one failure. There are 3 ways this can happen (SSF, SFS, FSS) so we multiply by 3 as well. The general formula is:
<span class="math display">\[P(X = x) \;=\; \binom{n}{x}\pi^x(1-\pi)^{n-x}\]</span>
<span class="math inline">\(x\)</span> is the number of successes, and <span class="math inline">\(n-x\)</span> is the number of failures. The symbol <span class="math inline">\(\binom{n}{x}\)</span> counts the number of ways you can have <span class="math inline">\(x\)</span> successes out of <span class="math inline">\(n\)</span> total tries.</p>
<hr />
<p>The shape of the binomial pmf depends on <span class="math inline">\(n\)</span>, the number of trails, and <span class="math inline">\(\pi\)</span>, the probability of success for any individual trial.</p>
<p>This binomial has <span class="math inline">\(n = 10\)</span>, so it covers all of the numbers from 0-10. The individual success probability is 0.5, an exact 50/50 chance to succeed or fail, so the “peak” of the graph is right in the middle.</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>This binomial also has <span class="math inline">\(n = 10\)</span>, but a bigger success probability of <span class="math inline">\(\pi = 0.7\)</span>. The peak is shifted to the right.</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>This binomial has <span class="math inline">\(n = 10\)</span> and a very small success probability of <span class="math inline">\(\pi = 0.1\)</span>. Notice how the bars for the higher numbers are extremely small. If the success rate for each trial is 10%, it’s incredibly unlikely that we hit that 10% success rate 10 times in a row.</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Finally, this binomial has <span class="math inline">\(n = 20\)</span> and <span class="math inline">\(\pi = 0.5\)</span>. We’re most likely to see a mix of successees and failures, which is why most of the graph is concentrated around the middle.</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<hr />
<p>We can use the R function <code>dbinom</code> as a shortcut for calculating binomial probabilities. Write <code>dbinom(x, n, pi)</code> as a shortcut for
<span class="math display">\[P(X = x) \;=\; \binom{n}{x}\pi^x(1-\pi)^{n-x}.\]</span>
For example, we can re-calculate <span class="math inline">\(P(X = 2)\)</span> in the plant genes example.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="random-variables.html#cb1-1" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">2</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">prob =</span> <span class="dv">9</span><span class="sc">/</span><span class="dv">16</span>)</span></code></pre></div>
<pre><code>## [1] 0.4152832</code></pre>
<div class="infobox exer">
<p>Let <span class="math inline">\(Y \sim Binom(5, 0.25)\)</span>. Use R <code>dbinom</code> for the following questions.</p>
<ul>
<li>What is <span class="math inline">\(P(Y = 1)\)</span> and what does the value mean?</li>
<li>What is <span class="math inline">\(P(Y \ge 1)\)</span>, and what does the value mean?</li>
</ul>
<p><span style="color:#8601AF">
According to R, P(Y = 1) is 0.396. This is the probability that we see exactly one success out of five total trials.
</span></p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="random-variables.html#cb3-1" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">1</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">prob =</span> <span class="fl">0.25</span>)</span></code></pre></div>
<pre><code>## [1] 0.3955078</code></pre>
<p><span style="color:#8601AF">
One way to find <span class="math inline">\(P(Y \ge 1)\)</span> is to use the complement rule. <span class="math inline">\(Y \ge 1\)</span> means we see at least one success, and the only way this doesn’t happen is if we get no successes, where <span class="math inline">\(Y = 0\)</span>. The probability is <span class="math inline">\(P(Y \ge 1) = 1 - P(Y = 0) = 0.763.\)</span>
</span></p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="random-variables.html#cb5-1" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">dbinom</span>(<span class="dv">0</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">prob =</span> <span class="fl">0.25</span>)</span></code></pre></div>
<pre><code>## [1] 0.7626953</code></pre>
<p><span style="color:#8601AF">
We can also add up the probabilities for 1, 2, 3, 4, and 5 with a bit of R cleverness. Below, <code>dbinom(1:5, 5, 0.25)</code> calculates all of the individual binomial probabilities from 1 to 5 successes. Then the <code>sum</code> function adds them together, giving us our final value.
</span></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="random-variables.html#cb7-1" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">5</span>, <span class="fl">0.25</span>)</span></code></pre></div>
<pre><code>## [1] 0.3955078125 0.2636718750 0.0878906250 0.0146484375 0.0009765625</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="random-variables.html#cb9-1" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">5</span>, <span class="fl">0.25</span>))</span></code></pre></div>
<pre><code>## [1] 0.7626953</code></pre>
</div>
<hr />
<p>One nice thing about working with binomial RVs is that we have shortcuts for calculating the mean and variance in terms of <span class="math inline">\(n\)</span> and <span class="math inline">\(\pi\)</span>. So if we know those values, we don’t have to go to the trouble of using the general expected value or variance formula. The expected value of a <span class="math inline">\(Binom(n, \pi)\)</span> RV is
<span class="math display">\[\mu \;=\; n\pi\]</span>
the product of # trials and success probability. The average number of successes goes up when we do more trials, and it goes up when we have a higher individual success rate. The variance of a <span class="math inline">\(Binom(n, \pi)\)</span> RV is
<span class="math display">\[\sigma^2 \;=\; n\pi(1-\pi).\]</span>
The uncertainty in the number of successes goes up when <span class="math inline">\(n\)</span> goes up. The uncertainty is biggest when <span class="math inline">\(\pi\)</span> and <span class="math inline">\(1-\pi\)</span> are both equal to 0.5. But if <span class="math inline">\(\pi\)</span> is close to 0 or close to 1, we’re less uncertain about whether we succeed or fail.</p>
<hr />
<p>Let’s re-calculate the mean and variance of <span class="math inline">\(X \sim Binom(3, \frac{9}{16})\)</span> in the genes example, using these new shortcuts.
<span class="math display">\[\mu \;=\; n\pi \;=\; 3\cdot \frac{9}{16} \;=\; 1.6875\]</span>
<span class="math display">\[\sigma^2 \;=\; n\pi(1-\pi) \;=\; 3\cdot\frac{9}{16}\cdot \frac{7}{16} \;=\; 0.738\]</span>
which is what we got before. The only discrepancy is because we did a bunch of rounding the first time.</p>
</div>
<div id="rules-of-expectation-and-variance" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Rules of expectation and variance<a href="random-variables.html#rules-of-expectation-and-variance" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s define another RV in our genes experiment. Suppose <span class="math inline">\(P\)</span> is the number of RY pea pods we harvest from the offspring after breeding the plants 3 times. If a pea plant produces 11 pods, and <span class="math inline">\(X\)</span> is the number of RY plants, then <span class="math inline">\(P = 11X\)</span>.</p>
<p>If the mean of <span class="math inline">\(X\)</span> is 1.6875, what should the mean of <span class="math inline">\(P\)</span> be? Intuitively, since there are 11 pea pods per plant, and 1.687 is the average number of RY plants, the average number of RY pods should be <span class="math inline">\(11\times 1.687\)</span>.</p>
<p>We can think about the mean, variance and other properties of <span class="math inline">\(P\)</span> in terms of <span class="math inline">\(X\)</span>. We have a number of rules for calculating the expectation and variance of a random variable using information we know about a different RV. For example, using <span class="math inline">\(E(X)\)</span> from before to find <span class="math inline">\(E(P)\)</span>.</p>
<hr />
<p>In general, let <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> be any RVs, and let <span class="math inline">\(c\)</span> be a constant. We will discuss the following rules of expectation:</p>
<ul>
<li>Expectation of a constant, <span class="math inline">\(E(c)\)</span></li>
<li>Expectation of a shifted RV, <span class="math inline">\(E(X + c)\)</span></li>
<li>Expectation of a scaled RV, <span class="math inline">\(E(cX)\)</span></li>
<li>Expectation of a sum, <span class="math inline">\(E(X + Y)\)</span></li>
</ul>
<p>What do you think each of these expressions would be equal to?</p>
<div class="infobox deff">
<ul>
<li><span class="math inline">\(E(c) = c\)</span></li>
<li><span class="math inline">\(E(X + c) = E(X) + c\)</span></li>
<li><span class="math inline">\(E(cX) = cE(X)\)</span></li>
<li><span class="math inline">\(E(X + Y) = E(X) + E(Y)\)</span></li>
</ul>
</div>
<ul>
<li>The expected value of a constant is just itself.</li>
<li>When you shift a RV by a constant amount, the center also shifts by that amount.</li>
<li>When a RV gets scaled, the center is scaled by the same amount.</li>
<li>Expectation is additive.</li>
</ul>
<p>The final property is very powerful - <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> need to be independent for it to be true.</p>
<hr />
<p>We will also discuss the following rules of variance:</p>
<ul>
<li>Variance of a constant, <span class="math inline">\(V(c)\)</span></li>
<li>Variance of a shifted RV, <span class="math inline">\(V(X + c)\)</span></li>
<li>Variance of a scaled RV, <span class="math inline">\(V(cX)\)</span></li>
<li>Variance of a sum, <span class="math inline">\(V(X + Y)\)</span>, where <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent.</li>
</ul>
<p>What do you think each of these expressions would be equal to?</p>
<div class="infobox deff">
<ul>
<li><span class="math inline">\(V(c) = 0\)</span></li>
<li><span class="math inline">\(V(X + c) = V(X)\)</span></li>
<li><span class="math inline">\(V(cX) = c^2V(X)\)</span></li>
<li><span class="math inline">\(V(X + Y) = V(X) + V(Y)\)</span> for independent <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span></li>
</ul>
</div>
<ul>
<li>A constant does not vary, and we’re always certain of its value.</li>
<li>If we shift <span class="math inline">\(X\)</span> to a different location on the number line, its spread does not change.</li>
<li>If we scale a RV, variance is scaled by that amount squared. This is because variance is in <em>squared units</em> compared to the original RV.</li>
<li>The addition rule can only be used if <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent. Variance is not additive in general!</li>
</ul>
<hr />
<p>A small car ferry runs a trip every hour. The number of vehicles per trip <span class="math inline">\(T\)</span> is random, depending on the number of customers. The average number of vehicles per trip is <span class="math inline">\(E(T) = 3.87\)</span>. The variance in the number of vehicles per trip is <span class="math inline">\(V(T) = 1.286^2\)</span>.</p>
<p>Customers pay 5 units of money per vehicle. So, the amount of money collected by the company on a randomly selected trip is <span class="math inline">\(M = 5T\)</span>. The fixed cost for the company is 20, so the profit they make on a trip is <span class="math inline">\(P = 5T - 20\)</span>.</p>
<div class="infobox exer">
<p>Find the mean and variance of both <span class="math inline">\(M\)</span> and <span class="math inline">\(P\)</span>: <span class="math inline">\(\mathbb{E}(M), \mathbb{V}(M), \mathbb{E}(P), \mathbb{V}(P)\)</span>.</p>
<p><span style="color:#8601AF">
Since <span class="math inline">\(M = 5T\)</span>, we need to make use of the rules for when we scale a RV.
<span class="math display">\[\begin{align}
E(M) &amp;= E(5T) \\
&amp;= 5E(T) \\
&amp;= 5(3.87) \\
&amp;= 19.35
\end{align}\]</span>
Similarly,
<span class="math display">\[\begin{align}
V(M) &amp;= V(5T) \\
&amp;= 5^2V(T) \\
&amp;= 5^2 1.286^2 \\
&amp;= (5\times 1.286)^2
\end{align}\]</span>
The variance of <span class="math inline">\(M\)</span> is <span class="math inline">\((5\times 1.286)^2\)</span> so the standard deviation of <span class="math inline">\(M\)</span> is just <span class="math inline">\((5\times 1.286)\)</span>.
</span></p>
<p><span style="color:#8601AF">
Since <span class="math inline">\(P = 5T - 20\)</span>, we need to make use of the rules for when we scale a RV and the rules for when we shift a RV by a fixed amount.
<span class="math display">\[\begin{align}
E(P) &amp;= E(5T - 20) \\
&amp;= 5E(T) - E(20) \\
&amp;= 5(3.87) - 20 \\
&amp;= -0.65
\end{align}\]</span>
Similarly,
<span class="math display">\[\begin{align}
V(P) &amp;= V(5T - 20) \\
&amp;= 5^2V(T) + 0 \\
&amp;= 5^2 1.286^2 \\
&amp;= (5\times 1.286)^2
\end{align}\]</span>
We see that the variance of <span class="math inline">\(P\)</span> is the same as the variance of <span class="math inline">\(M\)</span>. The fixed cost of 20 doesn’t change the variability in the profit.
</span></p>
</div>
</div>
<div id="normal-random-variables" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Normal random variables<a href="random-variables.html#normal-random-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The most important type of RV in statistics is a normal RV, or normal distribution. Before we discuss this, we need to learn about continuous probability.</p>
<p>Recall that RVs can be either <strong>discrete</strong> or <strong>continuous</strong>, depending on whether or not the variable can only take on specific values. A continuous random variable can take on any value in a specific range.</p>
<div class="infobox deff">
<p>The probability function of a continuous RV is called a <strong>probability density function</strong>, or pdf.</p>
</div>
<p>This works differently from a discrete probability function (pmf), so it has a different name.</p>
<p>A continuous RV can take on any value in a range, so we can’t list the values in a table. We draw the pdf as a smooth curve.</p>
<hr />
<p>It takes 10 to 15 minutes to drive to campus, depending on traffic. The curve of the pdf represents all possible driving times and their relative probabilities.</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Based on the height of the curve, a longer driving time is a bit more likely, and a really short driving time is a bit less likely.</p>
<p>A very important distinction is that for continuous RVs, probability is not given by the height of the curve. It’s given by the <em>area under</em> the curve. The area under the entire pdf is 1, since the probability that the time is between 10 and 15 minutes is 1 (guaranteed).</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>This section of area is <span class="math inline">\(P(12 \le \text{ driving time } \le 14)\)</span>. Since the entire area is 1, this area will be a number between 0 and 1.</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>The probability of an single value (like <span class="math inline">\(P(\text{driving time} = 12)\)</span> is 0. Since we’re working with a continuous process, the probability of the driving time being <em>exactly</em> 12 minutes down to the pico-second is infinitely improbable. It only makes sense to think about the probability of a range.</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<hr />
<p>The concepts of expectation and variance can also be applied to continuous random variables. The calculation is different (we won’t go over it since it requires calculus). But the interpretation is the same. Expectation is the typical value in the population, and variance is the spread of the population.</p>
<hr />
<div class="infobox deff">
<p>A <strong>normal</strong> random variable is a type of continuous RV whose distribution is shaped like a bell curve.</p>
</div>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>There are many real-world processes that have this sort of shape. For things like height, weight, test scores, you would expect most individuals to be somehwere in the middle. A few individuals are particularly high or particularly low.</p>
<p>Data sampled from a normal population will appear normal on a histogram.</p>
<p><img src="figs/desc/normal_hist.png" width="80%" /></p>
<hr />
<p>Suppose the height of all US males has a normal distribution centered at 70 inches. The normal pdf curve will be centered at 70.</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>What is the probability that a randomly chosen US male has height under 72 inches? This is the area under the bell curve, to the left of <span class="math inline">\(x = 72\)</span>.</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>This is the same as the proportion of US males who are less than 72 inches tall.</p>
<hr />
<p>To define a normal RV, we specify mean and variance, <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma^2\)</span>. The formula for drawing the normal pdf is
<span class="math display">\[\frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{1}{2}\big(\frac{x-\mu}{\sigma}\big)^2}.\]</span>
We won’t be working directly with this. The exponential equation makes a smooth bell curve shape, and the fraction normalizes it so that the area under the curve is 1.</p>
<p>Every normal RV is defined from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(\infty\)</span>. The tails go on forever. To specify that we’re working with a normal RV, we write <span class="math inline">\(X \sim N(mean, variance)\)</span> which is <span class="math inline">\(X \sim N(\mu, \sigma^2)\)</span>.</p>
<p>The bell-curve of the normal pdf is centered at <span class="math inline">\(\mu\)</span>, and its width is given by <span class="math inline">\(\sigma^2\)</span>. This is a normal RV that is centered at 0 and has variance 1:</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>This normal RV has a lower center and more spread.</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>This normal RV has a higher center and less spread.</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<hr />
<p>We can also define the spread of a normal RV in terms of its standard deviation, which is <span class="math inline">\(\sigma = \sqrt{\sigma^2}\)</span>. Interestingly, all normal populations have a specific proportion of items within 1, 2, and 3 standard deviations (<span class="math inline">\(\sigma\)</span>) from the mean.</p>
<p>Essentially, the values of a normal Rv are tightly concentrated around the mean, and this concentration is determined by <span class="math inline">\(\sigma\)</span>.</p>
<p><img src="figs/rvs/empirical_rule.png" /><!-- --></p>
<div class="infobox deff">
<p>This is the <strong>empirical rule</strong>. For a normal population, 68% of the population is within 1 standard deviation, 95% is within 2 standard deviations, and 99.7% is within 3 standard deviations. Mathematically, if <span class="math inline">\(X \sim N(\mu, \sigma^2)\)</span>,
<span class="math display">\[P(\mu-\sigma &lt; X &lt; \mu + \sigma) = 0.68\]</span>
<span class="math display">\[P(\mu-2\sigma &lt; X &lt; \mu + 2\sigma) = 0.95\]</span>
<span class="math display">\[P(\mu-3\sigma &lt; X &lt; \mu + 3\sigma) = 0.997\]</span></p>
</div>
<p>The tails on the normal bell curve go to infinity, but the area outside of 3 standard deviations is extremely tiny.</p>
<hr />
<p>A specific type of normal RV is a standard normal. This is used as a “reference point” for discussions of normal probabilities.</p>
<div class="infobox deff">
<p>A <strong>standard normal</strong> is a normal RV with mean 0 and variance 1 (and standard deviation 1). Use <span class="math inline">\(Z\)</span> to refer to a standard normal:
<span class="math display">\[Z \sim N(0, 1^2)\]</span></p>
</div>
<p>We can find probabilities about <em>any</em> normal RV from the standard normal distribution using a process called standardization.</p>
<div class="infobox deff">
<p>Let <span class="math inline">\(X \sim N(\mu, \sigma^2)\)</span> be any normal variable. It can be shown that
<span class="math display">\[Z = \frac{X - \mu}{\sigma}\]</span>
is <span class="math inline">\(N(0, 1^2)\)</span>. This transformation (subtract mean, divide by sd) is called <strong>standardization</strong>.</p>
</div>
<p>This can be done to any normal RV. <em>Any normal RV can be transformed into a standard normal RV, and a standard normal RV can be transformed back into any normal RV.</em></p>
<p>Thus, when we have a probability statement about some arbitrary normal RV, we can “translate” it into a statement about a standard normal RV.</p>
<hr />
<p>Let’s go back to the height example. Suppose the height of US males, <span class="math inline">\(X\)</span>, is normal with mean 70 inches and standard deviation 3. <span class="math inline">\(X \sim N(70, 3^2)\)</span>. (I prefer to write the variance as <span class="math inline">\(3^2\)</span> instead of <span class="math inline">\(9\)</span> for clarity).</p>
<p>What is <span class="math inline">\(P(X \le 72)\)</span>? We can find this by standardizing both sides. <span class="math display">\[\begin{align}
P(X \le 72) &amp;= P(X - 70 \le 72 - 70) \quad \quad \text{first, subtract mean from both sides} \\
&amp;= P\Big(\frac{X - 70}{3} \le \frac{72-70}{3}\Big) \quad \quad \text{then, divide both sides by sd} \\
&amp;= P\Big(Z \le \frac{2}{3}\Big) \quad \quad \text{the left side is a standard normal RV}
\end{align}\]</span></p>
<p>So, <span class="math inline">\(P(X \le 72) = P(Z \le \frac{2}{3})\)</span>. 72 on the height distribution corresponds to <span class="math inline">\(\frac{2}{3}\)</span> on the standard normal distribution. We call <span class="math inline">\(z = \frac{2}{3}\)</span> the z-score.</p>
<div class="infobox deff">
<p>A <strong>z-score</strong> is a value on the standard normal <span class="math inline">\(N(0, 1^2)\)</span> bell curve.</p>
</div>
<p>Since the standard normal is centered at 0 and has sd 1, a z-score tells us how many standard deviations we are away from the mean. The point 72 is <span class="math inline">\(\frac{2}{3}\)</span> of a standard deviation above the mean value of 70.</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>In general, for <span class="math inline">\(X \sim N(\mu, \sigma^2)\)</span>, we can write
<span class="math display">\[\mathbb{P}(X \le x) \;=\; \mathbb{P}\Big(Z \le \frac{x - \mu}{\sigma}\Big)\]</span></p>
<hr />
<p>How do we actually calculate a normal probability? It’s impossible to do this “by hand”, so we need to make use of external tools. Historically, probabilities were found with a standard normal table, which lists probabilities of a <span class="math inline">\(N(0, 1^2)\)</span> distributionn.</p>
<p>We’re going to use the R function <code>pnorm</code> (which stands for “probability normal”). R lets us find a probability either in terms of the standard normal, or in terms of the original normal distribution. By default, <code>pnorm</code> gives the area below a point on the standard normal curve.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="random-variables.html#cb11-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">2</span><span class="sc">/</span><span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 0.7475075</code></pre>
<p>There is 0.748 area to the left of <span class="math inline">\(\frac{2}{3}\)</span> on the standard normal curve (this corresponds to the red area above). Alternatively, if we take a random sample from the standard normal, there is a 74.8% chance that the value will end up being less than <span class="math inline">\(\frac{2}{3}\)</span>.</p>
<p>We can also specify the mean and standard deviation of the specific normal curve that we’re working with. Note that <code>pnorm</code> always wants the sd, not the variance.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="random-variables.html#cb13-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">72</span>, <span class="at">mean =</span> <span class="dv">70</span>, <span class="at">sd =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 0.7475075</code></pre>
<p>We get the exact same probability as before. So we can find this probability either directly, or through standardization. According to our model, 74.8% of US males are less than 72 inches tall.</p>
<hr />
<p>You may have noticed that I’m being a bit sloppy with whether I use “less than” or “less than or equal” for this problem. When we’re working with continuous probability, it actually doesn’t really matter. The probability of being exactly 72 is 0:</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>Since <span class="math inline">\(P(X = 72) = 0\)</span>,
<span class="math display">\[P(X \le 72) \;=\; P(X &lt; 72) + P(X = 72) \;=\; P(X &lt; 72).\]</span></p>
<hr />
<p>The weights of packages from a production line is normal with mean 16.1 oz and standard deviation 0.3 oz. <span class="math inline">\(W \sim N(16.1, 0.3^2)\)</span>.</p>
<div class="infobox exer">
<ul>
<li>Sketch the pdf (the normal bell curve) of <span class="math inline">\(W\)</span> and draw where a 16 ounce package falls on that distribution.</li>
</ul>
<p><span style="color:#8601AF">
The bell curve must be centered at <span class="math inline">\(\mu = 16.1\)</span>, since that’s the mean. We want to scale the x axis so that most of the area is within 3 standard deviations (frmo 15.2 to 17). The value 16 is very slightly below the mean, since it’s not even a full standard deviation away. You should try to do this on paper, but I’m doing this on a computer so I’ll make R do the work for me. :D
</span></p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<ul>
<li>What is the probability that a randomly chosen package weighs less than 16 ounces?</li>
</ul>
<p><span style="color:#8601AF">
Using standardization,
<span class="math display">\[P(W \le 16) \;=\; P\Big(\frac{W - 16}{0.3} \le \frac{16 - 16.1}{0.3}\Big) \;=\; P\Big(Z \le -\frac{1}{3}\Big).\]</span>
We can find this probability in R with the standardized score or with the original population distribution of <span class="math inline">\(W\)</span>. About 36.9% of the packages weigh less than 16.1 ounces.
</span></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="random-variables.html#cb15-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 0.3694413</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="random-variables.html#cb17-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">16</span>, <span class="fl">16.1</span>, <span class="fl">0.3</span>)</span></code></pre></div>
<pre><code>## [1] 0.3694413</code></pre>
<ul>
<li>What is the probability that a randomly chosen package has a weight between 15.5 and 16.5 ounces?</li>
</ul>
<p><span style="color:#8601AF">
We know how to use <code>pnorm</code> to find the area to the left of a certain value. But we need to find the area <em>between</em> two values. To do this, we need to find the area below 16.5, then <em>subtract</em> the area below 15.5. That will get us exactly the area between those two values.
</span></p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p><span style="color:#8601AF">
We need <span class="math inline">\(P(W \le 16.5) - P(W \le 15.5)\)</span> or in standardized scores, <span class="math inline">\(P(Z \le \frac{4}{3}) - P(Z \le -2)\)</span>. About 88.6% of packages are in this range.
</span></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="random-variables.html#cb19-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">16.5</span>, <span class="fl">16.1</span>, <span class="fl">0.3</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fl">15.5</span>, <span class="fl">16.1</span>, <span class="fl">0.3</span>)</span></code></pre></div>
<pre><code>## [1] 0.8860386</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="random-variables.html#cb21-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">4</span><span class="sc">/</span><span class="dv">3</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.8860386</code></pre>
</div>
<hr />
<p>To accompany our discussion of normal probability, we should also discuss normal quantiles. We’ve seen the concept of a quantile in the context of data, but it has the same definition for a population. For example, the 80th percentile on a normal distribution is the point such that 80% of the area (80% of the population) is below that point.</p>
<p>In R, normal quantiles are found with the <code>qnorm</code> function (quantile normal). This is the “opposite” of pnorm. We use <code>qnorm</code> when we are given a percentage or area, and want to know what value corresponds to that percentile.</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>For example, <code>qnorm(0.4)</code> finds the 40th percentile of a standard normal curve.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="random-variables.html#cb23-1" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.4</span>)</span></code></pre></div>
<pre><code>## [1] -0.2533471</code></pre>
<p>We can compare this functionality to <code>pnorm</code>, which we use if we are given an x value and need to find the area below that x value.</p>
<p><img src="04-randomvariables_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<hr />
<p>Let’s go back to the package weights that are normal with mean 16.1 oz and standard deviation 0.3 oz. <span class="math inline">\(W \sim N(16.1, 0.3^2)\)</span>.</p>
<div class="infobox exer">
<ul>
<li>Above what weight is the heaviest 1% of packages?</li>
</ul>
<p><span style="color:#8601AF">
Having 1% of the packages be above a certain weight means that 99% of weights are below, so this is asking us to find the 99th percentile. We can do this directly with the <code>qnorm</code> function by specifying the mean and sd.
</span></p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="random-variables.html#cb25-1" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.99</span>, <span class="at">mean =</span> <span class="fl">16.1</span>, <span class="at">sd =</span> <span class="fl">0.3</span>)</span></code></pre></div>
<pre><code>## [1] 16.7979</code></pre>
<p><span style="color:#8601AF">
We can also think about this in terms of z-scores. If a z-score is given by <span class="math inline">\(z = \frac{x-\mu}{\sigma}\)</span>, then we can re-arrange this to get <span class="math inline">\(x = z \sigma + \mu\)</span>. This expression lets us convert a value from Z to a value on another normal curve. We can do this with the 99th percentile of z to get the 99th percentile of <span class="math inline">\(W\)</span>.
</span></p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="random-variables.html#cb27-1" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.99</span>)<span class="sc">*</span><span class="fl">0.3</span> <span class="sc">+</span> <span class="fl">16.1</span></span></code></pre></div>
<pre><code>## [1] 16.7979</code></pre>
<p><span style="color:#8601AF">
We see that 99% of packages are below 16.798 ounces (and so 1% are above).
</span></p>
<ul>
<li>What package weight is the 3rd quartile?</li>
</ul>
<p><span style="color:#8601AF">
The 3rd quartile is the “three quarters” point of our population, the value such that 75% of the population is below and 25% is above. This is the same as the 75th percentile, so we can use the same method as before to find this value. We see that 75% of packages are less than 16.302 ounces.
</span></p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="random-variables.html#cb29-1" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.75</span>, <span class="at">mean =</span> <span class="fl">16.1</span>, <span class="at">sd =</span> <span class="fl">0.3</span>)</span></code></pre></div>
<pre><code>## [1] 16.30235</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="random-variables.html#cb31-1" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.75</span>)<span class="sc">*</span><span class="fl">0.3</span> <span class="sc">+</span> <span class="fl">16.1</span></span></code></pre></div>
<pre><code>## [1] 16.30235</code></pre>
<ul>
<li>Here’s a recap of material from earlier in this section. Suppose ten packages are randomly selected off the production line. What is the probability that exactly 6 packages have weights above 16 ounces?</li>
</ul>
<p><span style="color:#8601AF">
Checking whether or not a weight is above 16 ounces is a yes/no outcome, the packages are independent, and because the packages are all sampled from the same weight distribution, each has equal probability to exceed the threshold. These criteria (binary, independent, identical) are exactly what we need to define a binomial RV.
</span></p>
<p><span style="color:#8601AF">
If <span class="math inline">\(X\)</span> is the number of packages above 16 oz in the sample of ten, then <span class="math inline">\(X\)</span> is binomial with <span class="math inline">\(n = 10\)</span> trials. The success probability <span class="math inline">\(\pi\)</span> is the probability that any individual packages is above 16 ounces, which we can get with <code>pnorm</code>. The default behavior is to give an area below (in the lower tail), but we want an area above (in the upper tail). We can do this with subtraction, or by specifying <code>lower.tail = F</code>.
</span></p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="random-variables.html#cb33-1" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">16</span>, <span class="fl">16.1</span>, <span class="fl">0.3</span>)</span></code></pre></div>
<pre><code>## [1] 0.6305587</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="random-variables.html#cb35-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">16</span>, <span class="fl">16.1</span>, <span class="fl">0.3</span>, <span class="at">lower.tail =</span> F)</span></code></pre></div>
<pre><code>## [1] 0.6305587</code></pre>
<p><span style="color:#8601AF">
Any individual package has a probability 0.631 of being over 16 ounces, so the count of how many packages out of 6 are greater than 16 oz is <span class="math inline">\(X \sim Binom(10, 0.631)\)</span>. We can use R <code>dbinom</code> to get our final probability, which is <span class="math inline">\(P(X = 6) = 0.246.\)</span>
</span></p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="random-variables.html#cb37-1" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">6</span>, <span class="dv">10</span>, <span class="fl">0.631</span>)</span></code></pre></div>
<pre><code>## [1] 0.2457542</code></pre>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="probability.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="estimation.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/04-randomvariables.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
